### ISSUE TITLE
`export` assignment?

### ISSUE THREAD

**Issue by queckezz** [andreypopp/es6-module-jstransform#1]
The harmony spec is very unclear but from what I understand it should be possible to export like this:

``` js
export default prop;
```

right now this throws an error and only

``` js
export default = prop
```

is valid. Do you know if declaring a `export` without the equals is also valid? Awesome lib by the way, much less error prone than `es6-module-transpiler`!

**Comment by queckezz** [comment]
sweet, thanks!

**Comment by andreypopp** [comment]
Fixes in 0.1.2.

But it seems that es6 spec currently in flux regarding to modules... so expect some breaking changes when spec stabilizes.
