### ISSUE TITLE
Doesn't work in combination with es6-destructuring-jstransform

### ISSUE THREAD

**Issue by JannesMeyer** [andreypopp/es6-module-jstransform#10]
When using 

```
require('./visitors/es6-destructuring-jstransform').visitorList
require('./visitors/es6-module-jstransform').visitorList
```

together the following code gets transformed

``` javascript
export function test({title, body}) {
    return 'Title: ' + title + '\nBody: ' + body;
}
```

into this result:

``` javascript
function test(arg$0) {var title = arg$0.title, body = arg$0.body;
    return 'Title: ' + title + '\nBody: ' + body; module.exports.test = test;
}
```

which obviously doesn't export anything because the module.exports.test assignment ended up **inside** the function scope.

**Comment by andreypopp** [comment]
This library is broken and I don't think it makes sense to support it while es6 module spec is still in flux.

**Comment by JannesMeyer** [comment]
Oh. Okay, thank you for your quick answer! I guess we'll have to wait until we can use the new syntax.
