### ISSUE TITLE
allow early return statements?

### ISSUE THREAD

**Issue by jonathanong** [andreypopp/es6-module-jstransform#3]
i'm not sure if this is possible with es6 modules, but i do this with CJS stuff. this is a esprima issue, so we would have to wrap it in a silly closure for this to work.

**Comment by andreypopp** [comment]
If you are about having `return` at the top level I think that won't be possible because es6 modules are trying to be statically analysable.

TBH I even had issues with some tooling when it hit express or one of its deps because of early return.
